@startuml

title __BEAN's Class Diagram__\n

  namespace com.ocnyang.cartlayout {
    namespace bean {
      class com.ocnyang.cartlayout.bean.CartItemBean {
          # itemId : long
          - isChecked : boolean
          - itemType : int
          + getItemId()
          + getItemType()
          + isChecked()
          + setChecked()
          + setItemId()
          + setItemType()
      }
    }
  }
  

  namespace com.ocnyang.cartlayout {
    namespace bean {
      class com.ocnyang.cartlayout.bean.ChildItemBean {
          # groupId : int
          + getGroupId()
          + setGroupId()
      }
    }
  }
  

  namespace com.ocnyang.cartlayout {
    namespace bean {
      class com.ocnyang.cartlayout.bean.GroupItemBean {
          - childs : List<ChildItemBean>
          + getChilds()
          + setChilds()
      }
    }
  }
  

  namespace com.ocnyang.cartlayout {
    namespace bean {
      interface com.ocnyang.cartlayout.bean.ICartItem {
          {static} + TYPE_CHILD : int
          {static} + TYPE_GROUP : int
          {static} + TYPE_NORMAL : int
          {abstract} + getItemId()
          {abstract} + getItemType()
          {abstract} + isChecked()
          {abstract} + setChecked()
          {abstract} + setItemId()
          {abstract} + setItemType()
      }
    }
  }
  

  namespace com.ocnyang.cartlayout {
    namespace bean {
      interface com.ocnyang.cartlayout.bean.IChildItem {
          {abstract} + getGroupId()
          {abstract} + setGroupId()
      }
    }
  }
  

  namespace com.ocnyang.cartlayout {
    namespace bean {
      interface com.ocnyang.cartlayout.bean.IGroupItem {
          {abstract} + getChilds()
          {abstract} + setChilds()
      }
    }
  }
  

  com.ocnyang.cartlayout.bean.CartItemBean .up.|> com.ocnyang.cartlayout.bean.ICartItem
  com.ocnyang.cartlayout.bean.ChildItemBean .up.|> com.ocnyang.cartlayout.bean.IChildItem
  com.ocnyang.cartlayout.bean.ChildItemBean -up-|> com.ocnyang.cartlayout.bean.CartItemBean
  com.ocnyang.cartlayout.bean.GroupItemBean .up.|> com.ocnyang.cartlayout.bean.IGroupItem
  com.ocnyang.cartlayout.bean.GroupItemBean -up-|> com.ocnyang.cartlayout.bean.CartItemBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
