@startuml

title __CARTLAYOUT's Class Diagram__\n

  namespace com.ocnyang.cartlayout {
    abstract class com.ocnyang.cartlayout.CartAdapter {
        {static} + PAYLOAD_CHECKBOX : int
        # mContext : Context
        # mDatas : List<ICartItem>
        + CartAdapter()
        + addChild()
        + addChild()
        + addData()
        + addGroup()
        + addGroup()
        + addGroup()
        + addGroup()
        + addNormal()
        + addNormal()
        + checkedAll()
        + getData()
        + getItemCount()
        + getItemViewType()
        + onBindViewHolder()
        + onBindViewHolder()
        + onCreateViewHolder()
        + removeChecked()
        + removeChild()
        + setNewData()
        + setOnCheckChangeListener()
        {abstract} # getChildItemLayout()
        {abstract} # getChildViewHolder()
        {abstract} # getGroupItemLayout()
        {abstract} # getGroupViewHolder()
        {abstract} # getNormalItemLayout()
        {abstract} # getNormalViewHolder()
        # getOtherViewHolder()
        - addItem()
        - isHaveGroup()
    }
  }
  

  namespace com.ocnyang.cartlayout {
    class com.ocnyang.cartlayout.CartAdapter.OnCheckBoxClickListener {
        ~ mItemType : int
        ~ mPosition : int
        + onClick()
        - OnCheckBoxClickListener()
    }
  }
  

  namespace com.ocnyang.cartlayout {
    class com.ocnyang.cartlayout.ParseHelper {
        {static} + getChildList()
        {static} + getGroupBean()
        {static} + getGroupPosition()
    }
  }
  

  namespace com.ocnyang.cartlayout {
    class com.ocnyang.cartlayout.RecyclerViewWithContextMenu {
        {static} - TAG : String
        + RecyclerViewWithContextMenu()
        + RecyclerViewWithContextMenu()
        + RecyclerViewWithContextMenu()
        + showContextMenuForChild()
        # getContextMenuInfo()
    }
  }
  

  namespace com.ocnyang.cartlayout {
    class com.ocnyang.cartlayout.RecyclerViewWithContextMenu.RecyclerViewContextInfo {
        - mPosition : int
        + getPosition()
    }
  }
  

  com.ocnyang.cartlayout.CartAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.ocnyang.cartlayout.CartAdapter o-- com.ocnyang.cartlayout.listener.OnCheckChangeListener : onCheckChangeListener
  com.ocnyang.cartlayout.CartAdapter +-down- com.ocnyang.cartlayout.CartAdapter.OnCheckBoxClickListener
  com.ocnyang.cartlayout.CartAdapter.OnCheckBoxClickListener .up.|> android.view.View.OnClickListener
  com.ocnyang.cartlayout.RecyclerViewWithContextMenu -up-|> android.support.v7.widget.RecyclerView
  com.ocnyang.cartlayout.RecyclerViewWithContextMenu o-- com.ocnyang.cartlayout.RecyclerViewWithContextMenu.RecyclerViewContextInfo : mContextInfo
  com.ocnyang.cartlayout.RecyclerViewWithContextMenu +-down- com.ocnyang.cartlayout.RecyclerViewWithContextMenu.RecyclerViewContextInfo
  com.ocnyang.cartlayout.RecyclerViewWithContextMenu.RecyclerViewContextInfo .up.|> android.view.ContextMenu.ContextMenuInfo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
